### ISSUE TITLE
Nitzan notes

### ISSUE THREAD

**Issue by listguy** [itaibn9/Final-1-5#3]
Great work overall, your app looks good and delivers everything well (except the **white space** at the beginning of an input bug that i fell for too). Most of the components are responsive and it makes the site more vivid.
Two things i highly recommend to fix are:

1. When no tickets are shown all the elements **squeeze to the center** 
2. **Labels** buttons look awesome, responding to hovers and clicks - but do nothing. Either do something after a click or remove the responsive style.

I would also like to see the **restore button** responsive and more **spacing** between the header and content in each ticket

**Comment by AmitNirGit** [comment]
thanks for the review!
about your first comment - this is a UI and not a bug but  ill definitely fix the other comments you have metniond.
